name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ptonini-actions/config-git-user@v1
      - uses: ./
        with:
          tag_partial_versions: true